version: '3.8'

services:

    frontend:
        container_name: frontend
        build: 
            context: .
            dockerfile: Dockerfile
        volumes:
            - './ReactPjWebCourse'
            - '/ReactPjWebCourse/node_modules'
        ports: 
            - 8000:3000
        environment: 
            - CHOKIDAR_USEPOLLING=true
