version: '3.8'
services: 
    redis:
        container_name: redis
        image: redis
        ports:
            - "6379:6379"
        expose:
            - 6379
    express:
        container_name: api
        image: chiwidude/api
        ports:
            - 5000:4200
        environment: 
            - CHOKIDAR_USEPOLLING=true
        links: 
            - redis

