export  const godsData = [
    { id: 0, name: 'Gilgamesh', pantheon: 'Babylonian', role: "Warrior", dmg:"Physical" },
    { id: 1, name: 'Achilles', pantheon: 'Greek', role: "Warrior", dmg:"Physical" },
    { id: 2, name: 'Agni', pantheon: 'Hindu', role: "Mage", dmg:"Magical" },
    { id: 3, name: 'Ah Muzen Cab', pantheon: 'Mayan', role: "Hunter", dmg:"Physical" },
    { id: 4, name: 'Ah Puch', pantheon: 'Mayan', role: "Mage", dmg:"Mage" },
    { id: 5, name: 'Amaterasu', pantheon: 'Japanese', role: "Warrior", dmg:"Physical" },
    { id: 6, name: 'Anhur', pantheon: 'Egyptian', role: "Hunter", dmg:"Physical" },
    { id: 7, name: 'Anubis', pantheon: 'Egyptian', role: "Mage", dmg:"Magical" },
    { id: 8, name: 'Ao Kuang', pantheon: 'Chinese', role: "Mage", dmg:"Magical" },
    { id: 9, name: 'Aphrodite', pantheon: 'Greek', role: "Mage", dmg:"Magical" },
    { id: 10, name: 'Apollo', pantheon: 'Greek', role: "Hunter", dmg:"Physical" },
    { id: 11, name: 'Arachne', pantheon: 'Greek', role: "Assasin", dmg:"Physical" },
    { id: 12, name: 'Ares', pantheon: 'Greek', role: "Guardian", dmg:"Magical" },
    { id: 13, name: 'Artemis', pantheon: 'Greek', role: "Hunter", dmg:"Physical" },
    { id: 14, name: 'Artio', pantheon: 'Celtic', role: "Guardian", dmg:"Magical" },
    { id: 15, name: 'Athena', pantheon: 'Greek', role: "Guardian", dmg:"Magical" },
    { id: 16, name: 'Awilix', pantheon: 'Mayan', role: "Assasin", dmg:"Physical" },
    { id: 17, name: 'Baba Yaga', pantheon: 'Slavic', role: "Mage", dmg:"Magical" },
    { id: 18, name: 'Bacchus', pantheon: 'Roman', role: "Guardian", dmg:"Magical" },
    { id: 19, name: 'Bakasura', pantheon: 'Hindu', role: "Assasin", dmg:"Physical" },
    { id: 20, name: 'Baron Samedi', pantheon: 'Voodoo', role: "Mage", dmg:"Magical" },
    { id: 21, name: 'Bastet', pantheon: 'Egyptian', role: "Assasin", dmg:"Physical" },
    { id: 22, name: 'Bellona', pantheon: 'Roman', role: "Warrior", dmg:"Physical" },
    { id: 23, name: 'Cabrakan', pantheon: 'Mayan', role: "Guardian", dmg:"Magical" },
    { id: 24, name: 'Camazotz', pantheon: 'Mayan', role: "Assasin", dmg:"Physical" },
    { id: 25, name: 'Cerberus', pantheon: 'Greek', role: "Guardian", dmg:"Magical" },
    { id: 26, name: 'Cernunnos', pantheon: 'Celtic', role: "Hunter", dmg:"Physical" },
    { id: 27, name: 'Chaac', pantheon: 'Mayan', role: "Warrior", dmg:"Physical" },
    { id: 28, name: 'Chang\'e', pantheon: 'Chinese', role: "Mage", dmg:"Magical" },
    { id: 29, name: 'Chernobog', pantheon: 'Slavic', role: "Hunter", dmg:"Physical" },
    { id: 30, name: 'Chiron', pantheon: 'Greek', role: "Hunter", dmg:"Physical" },
    { id: 31, name: 'Chronos', pantheon: 'Greek', role: "Mage", dmg:"Magical" },
    { id: 32, name: 'Cthulhu', pantheon: 'Great Old Ones', role: "Guardian", dmg:"Magical" },
    { id: 33, name: 'Cu Chulainn', pantheon: 'Celtic', role: "Warrior", dmg:"Physical" },
    { id: 34, name: 'Cupid', pantheon: 'Roman', role: "Hunter", dmg:"Physical" },
    { id: 35, name: 'Daji', pantheon: 'Chinese', role: "Assasin", dmg:"Physical" },
    { id: 36, name: 'danzaburou', pantheon: 'Japanese', role: "Hunter", dmg:"Physical" },
    { id: 37, name: 'Discordia', pantheon: 'Roman', role: "Mage", dmg:"Magical" },
    { id: 38, name: 'Erlang Shen', pantheon: 'Chinese', role: "Warrior", dmg:"Physical" },
    { id: 39, name: 'Eset', pantheon: 'Egyptian', role: "Mage", dmg:"Magical" },
    { id: 40, name: 'Fafnir', pantheon: 'Norse', role: "Guardian", dmg:"Magical" },
    { id: 41, name: 'Fenrir', pantheon: 'Norse', role: "Assasin", dmg:"Physical" },
    { id: 42, name: 'Ganesha', pantheon: 'Hindu', role: "Guardian", dmg:"Magical" },
    { id: 43, name: 'Geb', pantheon: 'Egyptian', role: "Guardian", dmg:"Magical" },
    { id: 44, name: 'Guan Yu', pantheon: 'Chinese', role: "Warrior", dmg:"Physical" },
    { id: 45, name: 'Hachiman', pantheon: 'Japanese', role: "Hunter", dmg:"Physical" },
    { id: 46, name: 'Hades', pantheon: 'Greek', role: "Mage", dmg:"Magical" },
    { id: 47, name: 'He Bo', pantheon: 'Chinese', role: "Mage", dmg:"Magical" },
    { id: 48, name: 'Heimdallr', pantheon: 'Norse', role: "Hunter", dmg:"Physical" },
    { id: 49, name: 'Hel', pantheon: 'Norse', role: "Mage", dmg:"Magical" },
    { id: 50, name: 'Hera', pantheon: 'Greek', role: "Mage", dmg:"Magical" },
    { id: 51, name: 'Hercules', pantheon: 'Roman', role: "Warrior", dmg:"Physical" },
    { id: 52, name: 'Horus', pantheon: 'Egyptian', role: "Warrior", dmg:"Physical" },
    { id: 53, name: 'Hou Yi', pantheon: 'Chinese', role: "Hunter", dmg:"Physical" },
    { id: 54, name: 'Hun Batz', pantheon: 'Mayan', role: "Assasin", dmg:"Physical" },
    { id: 55, name: 'Izanami', pantheon: 'Japenese', role: "Hunter", dmg:"Physical" },
    { id: 56, name: 'Janus', pantheon: 'Roman', role: "Mage", dmg:"Magical" },
    { id: 57, name: 'Jing Wei', pantheon: 'Chinese', role: "Hunter", dmg:"Physical" },
    { id: 58, name: 'Jormungandr', pantheon: 'Norse', role: "Guardian", dmg:"Magical" },
    { id: 59, name: 'Kali', pantheon: 'Hindu', role: "Assasin", dmg:"Physical" },
    { id: 60, name: 'Khepri', pantheon: 'Egyptian', role: "Guardian", dmg:"Magical" },
    { id: 61, name: 'King Arthur', pantheon: 'Arthurian', role: "Warrior", dmg:"Physical" },
    { id: 62, name: 'Kukulkan', pantheon: 'Mayan', role: "Mage", dmg:"Magical" },
    { id: 63, name: 'Kumbhakarna', pantheon: 'Hindu', role: "Guardian", dmg:"Magical" },
    { id: 64, name: 'Kuzenbo', pantheon: 'Japanese', role: "Guardian", dmg:"Magical" },
    { id: 65, name: 'Loki', pantheon: 'Norse', role: "Assasin", dmg:"Physical" },
    { id: 66, name: 'Medusa', pantheon: 'Greek', role: "Hunter", dmg:"Physical" },
    { id: 67, name: 'Mercury', pantheon: 'Roman', role: "Assasin", dmg:"Physical" },
    { id: 68, name: 'Merlin', pantheon: 'Arthurian', role: "Mage", dmg:"Magical" },
    { id: 69, name: 'Mulan', pantheon: 'Chinese', role: "Warrior", dmg:"Physical" },
    { id: 70, name: 'Ne Zha', pantheon: 'Chinese', role: "Assasin", dmg:"Physical" },
    { id: 71, name: 'Neith', pantheon: 'Egyptian', role: "Hunter", dmg:"Physical" },
    { id: 72, name: 'Nemesis', pantheon: 'Greek', role: "Assasin", dmg:"Physical" },
    { id: 73, name: 'Nike', pantheon: 'Greek', role: "Warrior", dmg:"Physical" },
    { id: 74, name: 'Nox', pantheon: 'Greek', role: "Mage", dmg:"Magical" },
    { id: 75, name: 'Nu Wa', pantheon: 'Chinese', role: "Mage", dmg:"Magical" },
    { id: 76, name: 'Odin', pantheon: 'Norse', role: "Warrior", dmg:"Physical" },
    { id: 77, name: 'Olorun', pantheon: 'Yoruba', role: "Mage", dmg:"Magical" },
    { id: 78, name: 'Osiris', pantheon: 'Egyptian', role: "Warrior", dmg:"Physical" },
    { id: 79, name: 'Pele', pantheon: 'Polynesian', role: "Assasin", dmg:"Physical" },
    { id: 80, name: 'Persephone', pantheon: 'Greek', role: "Mage", dmg:"Magical" },
    { id: 81, name: 'Poseidon', pantheon: 'Greek', role: "Mage", dmg:"Magical" },
    { id: 82, name: 'Ra', pantheon: 'Egyptian', role: "Mage", dmg:"Magical" },
    { id: 83, name: 'Raijin', pantheon: 'Japanese', role: "Mage", dmg:"Magical" },
    { id: 84, name: 'Rama', pantheon: 'Hindu', role: "Hunter", dmg:"Physical" },
    { id: 85, name: 'Ratatoskr', pantheon: 'Norse', role: "Assasin", dmg:"Physical" },
    { id: 86, name: 'Ravana', pantheon: 'Hindu', role: "Assasin", dmg:"Physical" },
    { id: 87, name: 'Scylla', pantheon: 'Greek', role: "Mage", dmg:"Magical" },
    { id: 88, name: 'Serqet', pantheon: 'Egyptian', role: "Assasin", dmg:"Physical" },
    { id: 89, name: 'Set', pantheon: 'Egyptian', role: "Assasin", dmg:"Physical" },
    { id: 90, name: 'Skadi', pantheon: 'Norse', role: "Hunter", dmg:"Physical" },
    { id: 91, name: 'Sobek', pantheon: 'Egyptian', role: "Guardian", dmg:"Magical" },
    { id: 92, name: 'Sol', pantheon: 'Norse', role: "Mage", dmg:"Magical" },
    { id: 93, name: 'Sun Wukong', pantheon: 'Chinese', role: "Warrior", dmg:"Physical" },
    { id: 94, name: 'Susano', pantheon: 'Japanese', role: "Assasin", dmg:"Physical" },
    { id: 95, name: 'Sylvanus', pantheon: 'Roman', role: "Guardian", dmg:"Magical" },
    { id: 96, name: 'Terra', pantheon: 'Roman', role: "Guardian", dmg:"Magical" },
    { id: 97, name: 'Thanatos', pantheon: 'Greek', role: "Assasin", dmg:"Physical" },
    { id: 98, name: 'The Morrigan', pantheon: 'Celtic', role: "Mage", dmg:"Magical" },
    { id: 99, name: 'Thor', pantheon: 'Norse', role: "Assasin", dmg:"Physical" },
    { id: 100, name: 'Thoth', pantheon: 'Egyptian', role: "Mage", dmg:"Magical" },
    { id: 101, name: 'Tiamat', pantheon: 'Babylonian', role: "Mage", dmg:"Magical" },
    { id: 102, name: 'Tsukuyomi', pantheon: 'Japanese', role: "Assasin", dmg:"Physical" },
    { id: 103, name: 'Tyr', pantheon: 'Norse', role: "Warrior", dmg:"Physical" },
    { id: 104, name: 'Ullr', pantheon: 'Norse', role: "Hunter", dmg:"Physical" },
    { id: 105, name: 'Vamana', pantheon: 'Hindu', role: "Warrior", dmg:"Physical" },
    { id: 106, name: 'Vulcan', pantheon: 'Roman', role: "Mage", dmg:"Magical" },
    { id: 107, name: 'Xbalanque', pantheon: 'Mayan', role: "Hunter", dmg:"Physical" },
    { id: 108, name: 'Xing Tian', pantheon: 'Chinese', role: "Guardian", dmg:"Magical" },
    { id: 109, name: 'Yemoja', pantheon: 'Yoruba', role: "Guardian", dmg:"Magical" },
    { id: 110, name: 'Ymir', pantheon: 'Norse', role: "Guardian", dmg:"Magical" },
    { id: 111, name: 'Zeus', pantheon: 'Greek', role: "Mage", dmg:"Magical" },
    { id: 112, name: 'Zhong Kui', pantheon: 'Chinese', role: "Mage", dmg:"Magical" }]